CREATE SEQUENCE CATEGORIA_SEQ;

CREATE TABLE CATEGORIA(
    "ID_CATEGORIA"             NUMBER(19, 0) NOT NULL,
    "NOME"                      VARCHAR(50)  NOT NULL,
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA),
);

INSERT INTO CATEGORIA (ID_CATEGORIA, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Lazer');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Alimentação');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Supermercado');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Farmácia');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Outros');
