CREATE SEQUENCE CATEGORIA_SEQ;

CREATE TABLE CATEGORIA(
    "CODIGO"             BIGINT(20) NOT NULL,
    "NOME"               VARCHAR(50)  NOT NULL,
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (CODIGO),
);

INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Lazer');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Alimentação');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Supermercado');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Farmácia');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Outros');
INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Teste');
