CREATE SEQUENCE CATEGORIA_SEQ;

CREATE TABLE CATEGORIA(
    "ID_CATEGORIA"             NUMBER(19, 0) NOT NULL,
    "NOME"                      VARCHAR(50)  NOT NULL,
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA),
);
