INSERT INTO CATEGORIA (ID_CATEGORIA, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Lazer');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Alimentação');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Supermercado');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Farmácia');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME) VALUES (CATEGORIA_SEQ.nextval, 'Outros');

