CREATE SEQUENCE LANCAMENTO_SEQ;

CREATE TABLE LANCAMENTO (
	"CODIGO"                            BIGINT(20),
	"DESCRICAO"                         VARCHAR(50) NOT NULL,
	"DATA_VENCIMENTO"                  DATE NOT NULL,
	"DATA_PAGAMENTO"                   DATE,
	"VALOR"                              DECIMAL(10,2) NOT NULL,
	"OBSERVACAO"                         VARCHAR(100),
	"TIPO"                               VARCHAR(20) NOT NULL,
	"CODIGO_CATEGORIA" BIGINT(20)       NOT NULL,
	"CODIGO_PESSOA" BIGINT(20)          NOT NULL,
	CONSTRAINT LANCAMENTO_PK            PRIMARY KEY (CODIGO),
	CONSTRAINT LANCAMENTO_CATEGORIA_FK  FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA (CODIGO),
	CONSTRAINT LANCAMENTO_PESSOA_FK     FOREIGN KEY (CODIGO_PESSOA) REFERENCES PESSOA (CODIGO)
);

INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Salário mensal', '2017-06-10', null, 6500.00, 'Distribuição de lucros', 'RECEITA', 1, 1);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Bahamas', '2017-02-10', '2017-02-10', 100.32, null, 'DESPESA', 2, 2);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Top Club', '2017-06-10', null, 120, null, 'RECEITA', 3, 3);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'CEMIG', '2017-02-10', '2017-02-10', 110.44, 'Geração', 'RECEITA', 3, 4);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'DMAE', '2017-06-10', null, 200.30, null, 'DESPESA', 3, 5);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Extra', '2017-03-10', '2017-03-10', 1010.32, null, 'RECEITA', 4, 6);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Bahamas', '2017-06-10', null, 500, null, 'RECEITA', 1, 7);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Top Club', '2017-03-10', '2017-03-10', 400.32, null, 'DESPESA', 4, 8);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Despachante', '2017-06-10', null, 123.64, 'Multas', 'DESPESA', 3, 9);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Pneus', '2017-04-10', '2017-04-10', 665.33, null, 'RECEITA', 5, 10);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Café', '2017-06-10', null, 8.32, null, 'DESPESA', 1, 5);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Eletrônicos', '2017-04-10', '2017-04-10', 2100.32, null, 'DESPESA', 5, 4);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Instrumentos', '2017-06-10', null, 1040.32, null, 'DESPESA', 4, 3);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Café', '2017-04-10', '2017-04-10', 4.32, null, 'DESPESA', 4, 2);
INSERT INTO LANCAMENTO (CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA) values (LANCAMENTO_SEQ.nextval, 'Lanche', '2017-06-10', null, 10.20, null, 'DESPESA', 4, 1);
